version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
          paths: ~/.gradle
      - run:
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test

      # Store reports
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: core/build/reports
          destination: reports
      - store_artifacts:
          path: network/build/reports
          destination: reports

      # Store tests results
      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: network/build/test-results


